name: Test CI

on: push

jobs:
  build:
    name: Unit & Integration tests

    env:
      ETHEREUM_URL: ${{ secrets.ETHEREUM_URL }}
      POLYGON_URL: ${{ secrets.POLYGON_URL }}
      ARBITRUM_URL: ${{ secrets.ARBITRUM_URL }}
      OPTIMISM_URL: ${{ secrets.OPTIMISM_URL }}
      BASE_URL: ${{ secrets.BASE_URL }}
      CRONOS_URL: ${{ secrets.CRONOS_URL }}
      MANTLE_URL: ${{ secrets.MANTLE_URL }}
      BSC_URL: ${{ secrets.BSC_URL }}
      SEPOLIA_URL: ${{ secrets.SEPOLIA_URL }}
      GOERLI_URL: ${{ secrets.GOERLI_URL }}
      BASE_GOERLI_URL: ${{ secrets.BASE_GOERLI_URL }}
      CRONOS_TESTNET_URL: ${{ secrets.CRONOS_TESTNET_URL }}
      MANTLE_TESTNET_URL: ${{ secrets.MANTLE_TESTNET_URL }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install

      - name: Run unit tests
        run: forge test --match-path "test/unit/*" --force -vvv

      - name: Run integration tests
        run: forge test --match-path "test/integration/*" -vvv
