name: Test CI

on: push

jobs:
  build:
    name: Unit & Integration tests

    env:
      ETHEREUM_URL: ${{ secrets.ETHEREUM_URL }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install

      - name: Run unit tests
        run: forge test --match-path "test/unit/*" --force

      - name: Run integration tests
        run: forge test --match-path "test/integration/*"
